# -*- coding: utf-8 -*-
"""Week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3Xt39vdlSloN84Ds9SetEgZI-L9lgfj
"""

# Creating a program
# define our file names
# Reading a file
file_use = 'file.txt'
file =  open('file_use', 'r')
data = file.read()
print(data)

# write a file
write_file = open('file_use', 'w')
write_data = write_file.write('hello')

#Error Handling
try:
  with open('file_use', 'r') as file:
    data = file.read()
except FileNotFoundError:
  print('File not found')